name: agileflight
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.8.10
  - pip:
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.20.0
      - anyio==4.5.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - catkin-pkg==1.0.0
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - distro==1.9.0
      - docutils==0.20.1
      - einops==0.8.0
      - empy==3.3.4
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - gdown==5.2.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.4.9
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.14.2
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclassic==1.1.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.0
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nvtx-cu11==11.8.86
      - open3d==0.13.0
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rospkg==1.5.1
      - rpds-py==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli==2.0.2
      - tomlkit==0.13.2
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.2.0+cu118
      - torchaudio==2.2.0+cu118
      - torchvision==0.17.0+cu118
      - traitlets==5.14.3
      - triton==2.2.0
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uniplot==0.10.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - y-py==0.6.2
      - ypy-websocket==0.8.4
